version: '3.4'

volumes:
  datafiles:

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
        SA_PASSWORD: Store@2023
        ACCEPT_EULA: Y
    ports:
        - "1433:1433"
    volumes:
      - "./data/:/var/opt/mssql/data/"
      - "./log/:/var/opt/mssql/log/"
      - "./secrets/:/var/opt/mssql/secrets/"

  eventticket.services.eventcatalog:
    image: ${DOCKER_REGISTRY-}eventticketserviceseventcatalog
    build:
      context: .
      dockerfile: EventTicket.Services.EventCatalog/Dockerfile


  eventticket.services.ordering:
    image: ${DOCKER_REGISTRY-}eventticketservicesordering
    build:
      context: .
      dockerfile: EventTicket.Services.Ordering/Dockerfile


  eventticker.services.discount:
    image: ${DOCKER_REGISTRY-}eventtickerservicesdiscount
    build:
      context: .
      dockerfile: EventTicker.Services.Discount/Dockerfile

