version: '3.4'

volumes:
  datafiles:

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
        SA_PASSWORD: Store@2023
        ACCEPT_EULA: Y
    ports:
        - "1433:1433"
    volumes:
      - "./data/:/var/opt/mssql/data/"
      - "./log/:/var/opt/mssql/log/"
      - "./secrets/:/var/opt/mssql/secrets/"
  store.service.product:
    image: ${DOCKER_REGISTRY-}storeserviceproduct
    build:
      context: .
      dockerfile: Store.Service.Product/Dockerfile

  