version: '3.4'

services:
  store.service.product:
    image: ${DOCKER_REGISTRY-}storeserviceproduct
    build:
      context: .
      dockerfile: Store.Service.Product/Dockerfile

  mssql:
      image: mcr.microsoft.com/mssql/server
      environment:
        SA_PASSWORD: Store@2023
        ACCEPT_EULA: Y
      ports:
        - "1433:1433"